#!/bin/bash
#SBATCH --job-name=cellsnp-lite
#SBATCH --output=./logs/cellsnp-lite_%j.out
#SBATCH --error=./logs/cellsnp-lite_%j.err
#SBATCH --cpus-per-task=20
#SBATCH --mem=40G
#SBATCH -p general-cpu
#SBATCH --time=4:00:00

run_id="SRR9134578"
base_dir="./Phuc_10x"

# 2. Define Input / Output Paths
# Replace these paths with the actual locations on your system
CR_OUT_DIR="${base_dir}/${run_id}_run/outs"

# The BAM file generated by cellranger with 'create-bam true'
BAM_FILE="${CR_OUT_DIR}/possorted_genome_bam.bam"

# The filtered barcodes generated by cellranger
# Make sure to use the filtered barcodes, not the raw ones
BARCODE_FILE="${CR_OUT_DIR}/filtered_feature_bc_matrix/barcodes.tsv.gz"

# Reference SNPs VCF (e.g., 1000 Genomes project common SNPs)
VCF_REF="${base_dir}/vcf/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf.gz"

# Output directory for cellsnp-lite
min_maf=0.0
min_count=5
OUT_DIR="${base_dir}/cellsnp-lite_${run_id}_minmaf${min_maf}_mincount${min_count}"
mkdir -p "$OUT_DIR"

# 3. Run cellsnp-lite (Mode 1a: droplet-based single cells)
echo "Starting cellsnp-lite on $(date)"

srun \
  --container-image='quay.io/biocontainers/cellsnp-lite:1.2.3--ha0c3a46_6' \
  --container-workdir="${base_dir}" \
  --container-mounts="${base_dir}:${base_dir}" \
  cellsnp-lite \
    -s "$BAM_FILE" \
    -b "$BARCODE_FILE" \
    -O "$OUT_DIR" \
    -R "$VCF_REF" \
    -p "$SLURM_CPUS_PER_TASK" \
    --cellTAG CB \
    --UMItag UB \
    --minMAF $min_maf \
    --minCOUNT $min_count

echo "cellsnp-lite finished on $(date)"